# Generated by Django 2.1.7 on 2019-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20190416_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان بخش')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
