# Generated by Django 2.1.7 on 2019-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='tutorial',
            field=models.ForeignKey(default=None, on_delete='Restrict', to='tutorial.Tutorial', verbose_name='توتوریال'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='لینک'),
        ),
    ]
