# Generated by Django 2.1.7 on 2019-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20190416_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='مکان نسبی'),
        ),
    ]
