# Generated by Django 2.1.7 on 2019-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_links_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(blank=True, max_length=128, verbose_name='لینک'),
        ),
    ]
