# Generated by Django 2.1.7 on 2019-09-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20190728_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
