# Generated by Django 2.1.7 on 2019-09-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_links_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='english_title',
            field=models.CharField(blank=True, default=None, max_length=350, null=True, verbose_name='عنوان بخش انگلیسی'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان بخش'),
        ),
    ]
