# Generated by Django 2.1.7 on 2019-04-30 06:16

import apps.order_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0007_auto_20190425_0706'),
        ('registration', '0006_customer_is_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='نام فاکتور شونده')),
                ('file', models.FileField(blank=True, upload_to=apps.order_service.models.user_directory_path, verbose_name='فایل')),
                ('is_finished', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, default='PR', max_length=40, verbose_name='کد')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('customer', models.ForeignKey(on_delete='Cascade', to='registration.Customer', verbose_name='سفارش دهنده')),
                ('service', models.ForeignKey(on_delete='DoNothing', to='service.Service', verbose_name='سرویس')),
            ],
        ),
    ]
