# Generated by Django 2.1.7 on 2019-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_auto_20190430_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
