# Generated by Django 2.1.7 on 2019-04-30 07:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0004_orderservice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
