# Generated by Django 2.1.7 on 2019-04-30 07:17

import apps.order_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0005_auto_20190430_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='file',
            field=models.FileField(blank=True, default='raw_data.csv', upload_to=apps.order_service.models.user_directory_path, verbose_name='فایل'),
        ),
    ]
