# Generated by Django 2.1.7 on 2019-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0006_auto_20190430_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='کد'),
        ),
    ]
