# Generated by Django 2.1.7 on 2019-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0009_auto_20190502_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='فایل'),
        ),
    ]
