# Generated by Django 2.1.7 on 2019-05-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0010_auto_20190502_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='code',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='کد'),
        ),
    ]
