# Generated by Django 2.1.7 on 2019-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0011_auto_20190507_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام فاکتور شونده'),
        ),
    ]
