# Generated by Django 2.1.7 on 2019-12-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0012_auto_20190728_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='receiving_date',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
