# Generated by Django 2.1.7 on 2019-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyanTucagene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='لوگو')),
                ('summary', models.TextField(max_length=1500, verbose_name='خلاصه (صفحه اصلی)')),
                ('phone_number', models.IntegerField(verbose_name='تلفن')),
                ('address', models.TextField(max_length=300, verbose_name='آدرس')),
                ('about', models.TextField(max_length=3000, verbose_name='درباره شرکت')),
                ('fax', models.IntegerField(verbose_name='فکس')),
            ],
        ),
    ]
