# Generated by Django 2.1.7 on 2019-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0003_auto_20190514_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
