# Generated by Django 2.1.7 on 2019-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0004_royantucagene_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='instagram',
            field=models.URLField(default='', verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='royantucagene',
            name='telegram',
            field=models.URLField(default='', verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='royantucagene',
            name='twitter',
            field=models.URLField(default='', verbose_name='توییتر'),
        ),
    ]
