# Generated by Django 2.1.7 on 2019-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0006_auto_20190610_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='logo2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='لوگو۲'),
        ),
    ]
