# Generated by Django 2.1.7 on 2019-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0007_royantucagene_logo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royantucagene',
            name='address',
            field=models.TextField(max_length=3000, verbose_name='آدرس'),
        ),
    ]
