# Generated by Django 2.1.7 on 2019-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0008_auto_20190728_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینکداین'),
        ),
    ]
