# Generated by Django 2.1.7 on 2020-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0009_royantucagene_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='moto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='شعار'),
        ),
    ]
