# Generated by Django 2.1.7 on 2020-01-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royan_admin', '0010_royantucagene_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='royantucagene',
            name='address_english',
            field=models.TextField(blank=True, default='', max_length=3000, null=True, verbose_name='آدرس انگلیسی'),
        ),
    ]
