# Generated by Django 2.1.7 on 2019-03-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='عنوان خبر (فارسی)')),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.CharField(default='', max_length=500, verbose_name='خلاصه خبر (فارسی)')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='متن خبر (فارسی)')),
                ('english_title', models.CharField(blank=True, default='', max_length=150, verbose_name='عنوان خبر (انگلیسی)')),
                ('english_summary', models.CharField(blank=True, default='', max_length=500, verbose_name='خلاصه خبر (انگلیسی)')),
                ('english_description', models.TextField(blank=True, default='', max_length=2000, verbose_name='متن خبر (انگلیسی)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
        ),
    ]
