# Generated by Django 2.1.7 on 2019-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام زمینه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='field',
            field=models.ForeignKey(on_delete='Restrict', to='service.Field', verbose_name='زمینه\u200cی سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام سرویس'),
        ),
    ]
