# Generated by Django 2.1.7 on 2019-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190407_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/banner.jpg', null=True, upload_to='', verbose_name='فرم ثبت سفارش'),
        ),
    ]
