# Generated by Django 2.1.7 on 2019-04-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, default='front/primer.xls', null=True, upload_to='', verbose_name='فرم ثبت سفارش'),
        ),
    ]
