# Generated by Django 2.1.7 on 2019-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_has_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fields',
            field=models.FileField(blank=True, default='front/form.csv', null=True, upload_to='', verbose_name='فیلدهای فرم ثبت نام'),
        ),
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فرم ثبت سفارش'),
        ),
    ]
