# Generated by Django 2.1.7 on 2019-04-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190425_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fields',
            field=models.FileField(blank=True, default='form.csv', null=True, upload_to='', verbose_name='فیلدهای فرم ثبت نام'),
        ),
    ]
