# Generated by Django 2.1.7 on 2019-05-01 03:41

import apps.service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190425_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fields',
            field=models.FileField(blank=True, default='form.csv', null=True, upload_to=apps.service.models.fields_directory_path, verbose_name='فیلدهای فرم ثبت نام'),
        ),
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.service.models.file_directory_path, verbose_name='فرم ثبت سفارش'),
        ),
    ]
