# Generated by Django 2.1.7 on 2019-05-07 04:08

import apps.service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190501_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fields',
            field=models.FileField(blank=True, null=True, upload_to=apps.service.models.fields_directory_path, verbose_name='فیلدهای فرم ثبت نام'),
        ),
    ]
