# Generated by Django 2.1.7 on 2019-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190507_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
