# Generated by Django 2.1.7 on 2019-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='لوگو'),
        ),
    ]
