# Generated by Django 2.1.7 on 2019-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_service_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام زمینه')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='عکس')),
                ('field', models.ForeignKey(on_delete='Restrict', to='service.Field', verbose_name='زمینه\u200c')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='field2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='Restrict', to='service.Field2', verbose_name='زمینه\u200cی دوم سرویس'),
        ),
    ]
