# Generated by Django 2.1.4 on 2019-02-21 11:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(verbose_name='شماره تلفن ثابت')),
                ('fax', models.IntegerField(null=True, verbose_name='فکس')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده است')),
                ('referee', models.CharField(max_length=20, null=True, verbose_name='معرف')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.Customer')),
                ('organization_name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('post', models.CharField(max_length=100, verbose_name='سمت')),
                ('submit_id', models.IntegerField(verbose_name='شماره ثبت')),
                ('economic_id', models.IntegerField(verbose_name='شماره اقتصادی')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('registration.customer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.Customer')),
                ('national_id', models.IntegerField(verbose_name='کد ملی')),
                ('education', models.CharField(max_length=100, verbose_name='تحصیلات')),
                ('org', models.CharField(max_length=100, verbose_name='موسسه/آموزشگاه/سازمان')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('registration.customer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
