# Generated by Django 2.1.4 on 2019-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190224_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
