# Generated by Django 2.1.7 on 2019-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190226_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=100, verbose_name='تحصیلات'),
        ),
    ]
