# Generated by Django 2.1.7 on 2019-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190301_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(max_length=100, null=True, verbose_name='تحصیلات'),
        ),
    ]
