# Generated by Django 2.1.7 on 2019-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190301_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_person',
            field=models.BooleanField(default=False),
        ),
    ]
