# Generated by Django 2.1.7 on 2019-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_customer_is_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cellphone_number',
            field=models.BigIntegerField(verbose_name='شماره تلفن همراه'),
        ),
    ]
