# Generated by Django 2.1.7 on 2019-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0006_customer_is_person'),
        ('service', '0005_service_has_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('is_finished', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete='Cascade', to='registration.Customer', verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete='DoNothing', to='service.Service', verbose_name='سرویس')),
            ],
        ),
    ]
