# Generated by Django 2.1.7 on 2019-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='نام فاکتور شونده'),
        ),
    ]
