# Generated by Django 2.1.7 on 2019-05-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_customer_is_person'),
        ('message', '0002_message_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='Sender',
        ),
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(default=True, on_delete='Cascade', related_name='customer', to='registration.Customer', verbose_name='مشتری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_sender',
            field=models.BooleanField(default=True, verbose_name='مشتری پیام را فرستاده'),
        ),
    ]
