# Generated by Django 2.1.7 on 2019-05-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190501_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='DoNothing', related_name='parent_message', to='message.Message'),
        ),
    ]
