# Generated by Django 2.1.7 on 2019-05-01 01:42

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190501_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
