# Generated by Django 2.1.7 on 2019-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='آیا به اتمام رسیده است؟'),
        ),
    ]
