# Generated by Django 2.1.7 on 2019-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_product', '0002_orderproduct_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='توضیحات اضافه'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
