# Generated by Django 2.1.7 on 2019-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharea',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
    ]
