# Generated by Django 2.1.7 on 2019-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190416_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('authors', models.CharField(max_length=200, verbose_name='نویسندگان')),
                ('summary', models.TextField(max_length=1000, verbose_name='چکیده')),
                ('paper', models.FileField(upload_to='', verbose_name='مقاله')),
                ('research_area', models.ForeignKey(on_delete='Restrict', to='research.ResearchArea', verbose_name='زمینه تحقیقاتی')),
            ],
        ),
    ]
