# Generated by Django 2.1.7 on 2019-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=400, verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.TextField(max_length=10000, verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='description',
            field=models.TextField(max_length=4000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
