# Generated by Django 2.1.7 on 2019-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20190728_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=128, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='مقاله'),
        ),
    ]
