# Generated by Django 2.1.7 on 2019-03-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
