# Generated by Django 2.1.7 on 2019-03-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190318_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='english_description',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='متن خبر (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='news',
            name='english_summary',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='خلاصه خبر (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='news',
            name='english_title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='عنوان خبر (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=2000, verbose_name='متن خبر (فارسی)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(default='', max_length=500, verbose_name='خلاصه خبر (فارسی)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='عنوان خبر (فارسی)'),
        ),
    ]
