# Generated by Django 2.1.7 on 2019-03-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190318_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
